/*********************************************
 * Thinc Client
 * Amortya Ray & Divya Arora
 * {ar2566, da2254} @columbia.edu
 * Fall 2006-Fall 2007
 *********************************************/

package thinc;

public class ThinClientInit extends javax.swing.JFrame {

	/** Creates new form ThinClientInit */
	public ThinClientInit() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {
		lblHost = new javax.swing.JLabel();
		txtHost = new javax.swing.JTextField();
		txtPort = new javax.swing.JTextField();
		lblPort = new javax.swing.JLabel();
		jProgressBar1 = new javax.swing.JProgressBar();
		txtHost1 = new javax.swing.JTextField();
		lblHost1 = new javax.swing.JLabel();
		lblHost2 = new javax.swing.JLabel();
		jProgressBar2 = new javax.swing.JProgressBar();
		jPasswordField1 = new javax.swing.JPasswordField();
		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		lblPort1 = new javax.swing.JLabel();
		txtPort1 = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();

		getContentPane().setLayout(null);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		lblHost.setText("Host:");
		getContentPane().add(lblHost);
		lblHost.setBounds(20, 40, 40, 14);

		txtHost.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtHostActionPerformed(evt);
			}
		});

		getContentPane().add(txtHost);
		txtHost.setBounds(60, 40, 170, 19);

		getContentPane().add(txtPort);
		txtPort.setBounds(60, 70, 170, 19);

		lblPort.setText("Port:");
		getContentPane().add(lblPort);
		lblPort.setBounds(20, 70, 40, 14);

		getContentPane().add(jProgressBar1);
		jProgressBar1.setBounds(60, 100, 170, 18);

		getContentPane().add(txtHost1);
		txtHost1.setBounds(60, 190, 170, 19);

		lblHost1.setText("Usrnm:");
		getContentPane().add(lblHost1);
		lblHost1.setBounds(20, 190, 40, 14);

		lblHost2.setText("Pswd:");
		getContentPane().add(lblHost2);
		lblHost2.setBounds(20, 220, 40, 14);

		getContentPane().add(jProgressBar2);
		jProgressBar2.setBounds(60, 250, 170, 18);

		getContentPane().add(jPasswordField1);
		jPasswordField1.setBounds(60, 220, 170, 20);

		jCheckBox1.setText("Authentication");
		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});

		getContentPane().add(jCheckBox1);
		jCheckBox1.setBounds(20, 160, 100, 23);

		jCheckBox2.setText("SSL");
		getContentPane().add(jCheckBox2);
		jCheckBox2.setBounds(20, 130, 43, 23);

		jCheckBox3.setText("Sound");
		getContentPane().add(jCheckBox3);
		jCheckBox3.setBounds(20, 280, 60, 23);

		lblPort1.setText("Port:");
		getContentPane().add(lblPort1);
		lblPort1.setBounds(20, 310, 40, 14);

		txtPort1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtPort1ActionPerformed(evt);
			}
		});

		getContentPane().add(txtPort1);
		txtPort1.setBounds(60, 310, 170, 19);

		jPanel1.setBackground(new java.awt.Color(102, 102, 0));
		jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(
				0, 0, 0), 1, true));
		getContentPane().add(jPanel1);
		jPanel1.setBounds(270, 160, 20, 60);

		pack();
	}

	// </editor-fold>//GEN-END:initComponents

	private void txtPort1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPort1ActionPerformed
	// TODO add your handling code here:
	}// GEN-LAST:event_txtPort1ActionPerformed

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox1ActionPerformed
	// TODO add your handling code here:
	}// GEN-LAST:event_jCheckBox1ActionPerformed

	private void txtHostActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtHostActionPerformed
	// TODO add your handling code here:
	}// GEN-LAST:event_txtHostActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ThinClientInit().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JProgressBar jProgressBar1;
	private javax.swing.JProgressBar jProgressBar2;
	private javax.swing.JLabel lblHost;
	private javax.swing.JLabel lblHost1;
	private javax.swing.JLabel lblHost2;
	private javax.swing.JLabel lblPort;
	private javax.swing.JLabel lblPort1;
	private javax.swing.JTextField txtHost;
	private javax.swing.JTextField txtHost1;
	private javax.swing.JTextField txtPort;
	private javax.swing.JTextField txtPort1;
	// End of variables declaration//GEN-END:variables

}
